language: php

php:
  - 5.5
  - 5.6

matrix:
  allowed_failures:
    - php: 7.0
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - php app/console server:start -vvv --env=dev

script:
  - ./bin/phpspec run --config=test/phpspec.yml -vvv
  - ./bin/behat --config=test/behat.yml -vvv --suite=dashboardhub_app
