dashboard_hub_pipeline_dashboard:
    resource: "@DashboardHubPipelineDashboardBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
